### PR TITLE
Correct publishing to Gradle Plugins portal

### LINKED ISSUE #2: gradle gauge artefacts 1.7.1 and 1.7.2 are empty on https://plugins.gradle.org/m2
The deployments for version 1.7.2 (and 1.7.1) on https://plugins.gradle.org/m2 failed.

- https://plugins.gradle.org/m2/gradle/plugin/com/thoughtworks/gauge/gradle/gauge-gradle-plugin/1.7.1/
- https://plugins.gradle.org/m2/gradle/plugin/com/thoughtworks/gauge/gradle/gauge-gradle-plugin/1.7.2/
- 

All artefacts are empty.

The latest one that does work is 1.4.5

e.g. messge for 1.7.1: pom file

NoSuchKeyThe specified key does not exist.gradle.plugin.com.thoughtworks.gauge.gradle/gauge-gradle-plugin/1.7.1/0be2683d3982dbd4da379e7a98dc86d28dd9a794c52954b0955fd0ba45dee55b/gauge-gradle-plugin-1.7.1.pomF62543E18335B8256tOY0oj1c3glWOgxcA6yDzrbvichJBq0dukm7WJKEHiQpc57+mZHQdoQ/7FgTlChH0RjIcyrrWg=

### LINKED ISSUE #5: Maybe there shouldn't have "apply plugin:'application'"
When I build project by `'gradle build'`, there occur a error tips that "`No value has been specified for property 'mainClassName'`", Usually Gauge project didn't have main class, so I think there shouldn't have `apply plugin:'application'`

### PR DESCRIPTION
**Pull request by chadlwilson**
**Motivation**

The Plugins DSL is the modern way forward with Gradle - plugins should work with this much more concise DSL. The easiest way to do so is to publish them to the Plugins Portal.

Resolves #2 (hopefully)
Resolves #5 

**Changes Made**

* Followed guide [here](https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/) to correct publishing DSL
* Switched to use of the plugins DSL within the Gradle files
* Tidied up some minor broken pieces - sample not working; syntax of binTrayUpload not working
* Bumped Gradle Wrapper version

**For maintainer to do**

* `./gradlew publishPlugins`... hopefully; assuming still have api key for the Gradle Plugins Portal used to originally publish the plugin and ownership of the com.thoughtworks group
* Perhaps would be good to create a `1.7.4-rc1` and I can help test? I can also help update the README and samples

### CODE REVIEW

**Comment by chadlwilson** [comment]
@gaugebot recheck the pull request.

**Comment by chadlwilson** [comment]
@nehashri Thanks for merging! Are you able to help test publishing/create a release somehow so I can take this forward? I created #24 to setup a build; but not sure what else needs to be done, since I understand you are just starting to take over ownership of this plugin.

I guess we will need to figure our whether Thoughtworks/Gauge community have the right permissions to publish to the `com.thoughtworks` group on the Gradle Plugins portal and Bintray, or whether we need to publish under a new plugin identifier.

**Comment by nehashri** [comment]
@chadlwilson No we haven't tested the publishing this plugin yet. Gauge team will be maintaining this plugin hereon. We have asked @manupsunny to transfer the plugin ownership to Gauge. We are still waiting for the transfer to be completed. Once it is done, we will be able to test publishing the plugin.

**Comment by chadlwilson** [comment]
Awesome, thank you!

I have another couple of PRs lined up which I'll seek to submit in the
meantime as I guess this might take a bit.

If there are some conventions you are following in terms of producing
changelogs or otherwise automating releases that you'd like some help
aligning this plugin with, I'd be happy to help where I can.

**Comment by nehashri** [comment]
@chadlwilson Thank you. Looking forward to your PRs.
Also, I will let you know if there is any help required here.

**Pull request merged**
